# 广播（Broadcasting）实例 

例子一：

In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [2]:
cal  = A.sum(axis = 0)   # 竖方向求和
print(cal)

[  59.   239.   155.4   76.9]


In [3]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


例子二：

In [4]:
b = np.array([[1,2,3],
              [4,5,6]])

c = np.array([100,200,300])  # [1,n] 拓展为 [2,n]

d = b + c
print(d)

[[101 202 303]
 [104 205 306]]


例子三：

In [6]:
b = np.array([1,2,3])  # 行向量 [1*3]

c = np.array([[4],[5],[6]]) # 列向量 [3*1]

d = b + c
print(d)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


General Principle:
![](http://ogtxggxo6.bkt.clouddn.com/78u.png?imageslim)