In [3]:
from numpy import *

In [4]:
U,sigma,Vt = linalg.svd([[1,1],[7,7]])

In [5]:
U

array([[-0.14142136, -0.98994949],
       [-0.98994949,  0.14142136]])

In [6]:
sigma

array([ 10.,   0.])

In [8]:
Vt

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [9]:
U[1
]

array([-0.98994949,  0.14142136])

In [28]:
U1 = U[:,0]

In [29]:
U1=U1.reshape(-1,1)

In [20]:
sigma1=sigma[0]

In [31]:
Vt1 = Vt[0,:]

In [33]:
Vt1

array([-0.70710678, -0.70710678])

In [32]:
Vt

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [16]:
type(Vt)

numpy.ndarray

In [21]:
a = dot(U1,sigma1)

In [22]:
a

array([-1.41421356, -9.89949494])

In [23]:
dot(a,Vt1)

7.9999999999999982

In [24]:
Vt1

array([-0.70710678, -0.70710678])

In [25]:
Vt1 = Vt1.reshape(-1,1)

In [26]:
Vt1

array([[-0.70710678],
       [-0.70710678]])

In [27]:
dot(a,Vt1)

array([ 8.])

In [34]:
a =dot(U1,sigma1)

In [35]:
a

array([[-1.41421356],
       [-9.89949494]])

In [36]:
dot(a,Vt1)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [40]:
Vt1 = Vt1.reshape(1,-1)

In [41]:
Vt1

array([[-0.70710678, -0.70710678]])

In [42]:
dot(a,Vt1)

array([[ 1.,  1.],
       [ 7.,  7.]])